candidateTest: test.cpp
	g++ test.cpp candidate.cpp ../alphabetValuesHandler/alphabetValuesHandler.cpp -o test

candidateValueChangeTest: testValueChange.cpp
	g++ testValueChange.cpp candidate.cpp ../alphabetValuesHandler/alphabetValuesHandler.cpp -o test
