cryptoarithmetic: aplication.cpp executionHandler/executionHandler.cpp population/population.cpp candidate/candidate.cpp alphabetValuesHandler/alphabetValuesHandler.cpp common/config.hpp
	g++ aplication.cpp executionHandler/executionHandler.cpp population/population.cpp candidate/candidate.cpp alphabetValuesHandler/alphabetValuesHandler.cpp -o cryptoarithmetic
