cryptoarithmetic: aplication.cpp
	g++ aplication.cpp executionHandler/executionHandler.cpp population/population.cpp candidate/candidate.cpp alphabetValuesHandler/alphabetValuesHandler.cpp -o cryptoarithmetic
