exs02: spperceptron.cpp exs02test.cpp
	g++ --std=c++11 pattern/pattern.cpp spperceptron.cpp exs02test.cpp -o exs02

exs03: spperceptron.cpp exs03test.cpp
	g++ --std=c++11 pattern/pattern.cpp spperceptron.cpp exs03test.cpp -o exs03
